export interface AssetData {
    BranchName: string;
    DepartmentName: string;
    CategoryName: string;
    FkInventoryType: string;
    InventoryTypeName: string;
    InventoryIsAssets: boolean;
    StoreName: string;
    FkStoreStaffManager: string | null;
    StoreStaffManagerName: string;
    StoreStaffManagerIdno: string;
    StaffAssignedName: string;
    StaffAssignedIdno: string;
    ContractorName: string;
    SponsorName: string;
    ManufacturerName: string;
    CountChildAssets: number;
    EnumType: string;
    EnumStatus: string;
    ChildAssets: any[]; 
    AuditLogs: any[]; 
    QuantityUOM: string;
    CostPriceText: string;
    SalesPriceText: string;
    OldSalesPriceText: string;
    MfgDateText: string;
    ExpireDateText: string;
    AssetAnnualDepreciateRateText: string;
    AssetInitialAssetAmountText: string;
    AssetVariationAmountText: string;
    AssetTotalAmountText: string;
    AssetPaidAmountText: string;
    AssetBalanceAmountText: string;
    CalcAssetCurrentDepreciationText: string;
    CalcAssetNetBookValueText: string;
    AssetAwardDateText: string;
    AssetExpectedCompletionDateText: string;
    AssetOperationalDateText: string;
    CalcAssetOperationalExpiryDateText: string;
    LastSyncDateText: string;
    _ParentAssetTagno: string;
    Type: string;
    Batchno: string;
    FkBranch: string;
    FkProductCategory: string;
    FkDepartment: string;
    FkStore: string | null;
    FkStaffAssigned: string | null;
    FkMerchantContractor: string | null;
    FkMerchantSponsor: string | null;
    FkMerchantManufacturer: string | null;
    Shelf: string;
    Tagno: string;
    Name: string;
    Description: string;
    FilePhotos: string;
    Model: string | null;
    Color: string;
    Size: string;
    Quantity: number;
    Uom: string;
    CostPrice: number;
    SalesPrice: number;
    OldSalesPrice: number;
    MfgDate: string;
    ExpireDate: string | null;
    QtyCritical: number;
    QtyReorder: number;
    Status: string;
    Remark: string;
    AssetAnnualDepreciateRate: number;
    AssetInitialAssetAmount: number;
    AssetVariationAmount: number;
    AssetTotalAmount: number;
    AssetPaidAmount: number;
    AssetBalanceAmount: number;
    CalcAssetCurrentDepreciation: number;
    CalcAssetNetBookValue: number;
    AssetAwardDate: string | null;
    AssetExpectedCompletionDate: string | null;
    AssetOperationalDate: string;
    CalcAssetOperationalExpiryDate: string;
    LastSyncDate: string;
    FkParent: string | null;
    ImportBatchno: string;
    ImportUpdateBatchno: string | null;
    Id: string;
    IdSeq: number;
    IsArchived: boolean;
    IsLock: boolean;
    CreatedBy: string;
    CreatedByName: string;
    CreatedDate: string;
    LastModifiedBy: string | null;
    LastModifiedByName: string;
    LastModifiedDate: string | null;
    CreatedDateText: string;
    LastModifiedDateText: string;
  }